{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0e4e67b5-4161-4274-8123-5de2e01e682f",
   "metadata": {},
   "outputs": [],
   "source": [
    "import asyncio\n",
    "from telegram import Update\n",
    "from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes\n",
    "\n",
    "# ВСТАВЬТЕ СВОИ ДАННЫЕ\n",
    "TOKEN = \"7590252411:AAHYnqKN7J3KamfDj2sWk5jBWoXc7nxR7mU\"\n",
    "OWNER_ID = 1877423571  # ID владельца (узнай у @userinfobot)\n",
    "\n",
    "async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):\n",
    "    \"\"\"Ответ на команду /start\"\"\"\n",
    "    user = update.effective_user\n",
    "    await update.message.reply_text(\n",
    "        f\"Привет, {user.first_name}!\\n\"\n",
    "        \"Я пересылаю твои сообщения моему владельцу.\"\n",
    "    )\n",
    "\n",
    "async def forward_to_owner(update: Update, context: ContextTypes.DEFAULT_TYPE):\n",
    "    \"\"\"Пересылает сообщения владельцу\"\"\"\n",
    "    user = update.effective_user\n",
    "    message = update.message\n",
    "    \n",
    "    # Формируем текст с информацией об отправителе\n",
    "    user_info = (\n",
    "        f\"📨 Новое сообщение для бота\\n\"\n",
    "        f\"👤 От: {user.first_name} {user.last_name or ''}\\n\"\n",
    "        f\"🆔 ID: {user.id}\\n\"\n",
    "        f\"📱 Username: @{user.username or 'нет'}\\n\"\n",
    "        f\"💬 Сообщение:\\n{message.text}\"\n",
    "    )\n",
    "    \n",
    "    # Отправляем владельцу\n",
    "    await context.bot.send_message(\n",
    "        chat_id=OWNER_ID,\n",
    "        text=user_info\n",
    "    )\n",
    "    \n",
    "    # Подтверждаем пользователю\n",
    "    await message.reply_text(\"✅ Сообщение отправлено владельцу!\")\n",
    "\n",
    "async def forward_media(update: Update, context: ContextTypes.DEFAULT_TYPE):\n",
    "    \"\"\"Пересылает медиафайлы владельцу\"\"\"\n",
    "    user = update.effective_user\n",
    "    \n",
    "    # Определяем тип файла\n",
    "    if update.message.photo:\n",
    "        file_type = \"📸 Фото\"\n",
    "        file_id = update.message.photo[-1].file_id\n",
    "    elif update.message.video:\n",
    "        file_type = \"🎥 Видео\"\n",
    "        file_id = update.message.video.file_id\n",
    "    elif update.message.document:\n",
    "        file_type = \"📎 Документ\"\n",
    "        file_id = update.message.document.file_id\n",
    "    elif update.message.audio:\n",
    "        file_type = \"🎵 Аудио\"\n",
    "        file_id = update.message.audio.file_id\n",
    "    elif update.message.voice:\n",
    "        file_type = \"🎤 Голосовое\"\n",
    "        file_id = update.message.voice.file_id\n",
    "    else:\n",
    "        return\n",
    "    \n",
    "    caption = (\n",
    "        f\"{file_type} от пользователя\\n\"\n",
    "        f\"👤 {user.first_name} {user.last_name or ''}\\n\"\n",
    "        f\"🆔 {user.id}\\n\"\n",
    "        f\"📱 @{user.username or 'нет'}\"\n",
    "    )\n",
    "    \n",
    "    # Пересылаем файл владельцу\n",
    "    await context.bot.send_file(\n",
    "        chat_id=OWNER_ID,\n",
    "        document=file_id,\n",
    "        caption=caption\n",
    "    )\n",
    "    \n",
    "    await update.message.reply_text(\"✅ Файл отправлен владельцу!\")\n",
    "\n",
    "async def error_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):\n",
    "    \"\"\"Обработка ошибок\"\"\"\n",
    "    print(f\"Ошибка: {context.error}\")\n",
    "    if update:\n",
    "        await update.message.reply_text(\"❌ Произошла ошибка\")\n",
    "\n",
    "def main():\n",
    "    \"\"\"Запуск бота\"\"\"\n",
    "    # Создаем приложение\n",
    "    app = Application.builder().token(TOKEN).build()\n",
    "    \n",
    "    # Добавляем обработчики\n",
    "    app.add_handler(CommandHandler(\"start\", start))\n",
    "    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, forward_to_owner))\n",
    "    app.add_handler(MessageHandler(filters.PHOTO, forward_media))\n",
    "    app.add_handler(MessageHandler(filters.VIDEO, forward_media))\n",
    "    app.add_handler(MessageHandler(filters.DOCUMENT, forward_media))\n",
    "    app.add_handler(MessageHandler(filters.AUDIO, forward_media))\n",
    "    app.add_handler(MessageHandler(filters.VOICE, forward_media))\n",
    "    \n",
    "    # Обработчик ошибок\n",
    "    app.add_error_handler(error_handler)\n",
    "    \n",
    "    print(\"Бот запущен...\")\n",
    "    app.run_polling(allowed_updates=Update.ALL_TYPES)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
